version: '3'

services:
  servico_db:
    build: ./servico_db
    container_name: servico_db
    ports:
      - "5001:5001"

  servico_api:
    build: ./servico_api
    container_name: servico_api
    ports:
      - "5000:5000"
    depends_on:
      - servico_db
